spring:
  datasource:
    platform: h2
    data: classpath:data.sql
    schema: classpath:schema.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  application:
    name: provider
server:
  port: 1031
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
     prefer-ip-address: true
     instance-id: ${spring.application.name}:${server.port}