server:
  port: 1005
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: ribbon
#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eureka:
   enabled: false
provider:
  ribbon:
    listOfServers: localhost:1001